#!/bin/bash


echo "enter your skill: "
read SKILL

echo "your $SKILL skill is high demand in IT industry"

read -p 'username: ' USER
read -sp 'password: ' pass

echo
echo "login successfull: user $USER"
